/**
 * Build the Codex plugin's copies of djinn's agents, commands and contracts.
 * Codex installs only adapters/codex/plugin/ into its cache, so a skill
 * there cannot read plugins/djinn/. This copies every agent file, every
 * command file and CONTRACTS.md in, each behind a generated-file comment
 * that names its
 * source and the source's SHA-256. plugins/djinn stays the only copy
 * anyone edits. The Claude frontmatter is kept: each agent's own text
 * refers to it, and its tools line says which agents are read-only.
 *
 * Written by Claude Opus 5.5 for Donald, 2026-10-05. Status: tested, not
 * reviewed.
 *
 * Usage, from anywhere:
 *   node adapters/codex/build.mjs            write the copies
 *   node adapters/codex/build.mjs --check    exit 1 and name every copy
 *                                            that is stale, missing or extra
 * --src <dir> and --out <dir> override the two folders, for tests.
 *
 * @interacts  reads plugins/djinn/{agents,commands}/*.md,
 *             plugins/djinn/scripts/*.mjs, plugins/djinn/templates/*,
 *             plugins/djinn/CONTRACTS.md and plugins/djinn/guide.md (the
 *             viewer's guide page); writes the same paths under
 *             adapters/codex/plugin/, and deletes a copy in a copied folder
 *             whose source is gone. setup-project.mjs strips the YAML
 *             marker when it drafts a project's config from the template. The skills under
 *             plugin/skills/ follow the commands/ copies. Output is a pure function of the
 *             sources: no dates, no git calls.
 * @deps       node:fs, node:path, node:crypto, node:url. No packages.
 * @complexity O(f), f source files (44 today)
 * @alloc      one source and one output string per file, released per file
 */

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '../..');

const CONFIG = {
  src: join(REPO, 'plugins/djinn'),
  out: join(HERE, 'plugin'),
  // Each copied folder and the files it takes; the marker comment follows
  // the file's language.
  copiedDirs: { agents: /\.md$/, commands: /\.md$/, scripts: /\.mjs$/, templates: /\.(md|yaml)$/ },
  singleFiles: ['CONTRACTS.md', 'guide.md'],
};

function parseArgs(argv) {
  const opts = { check: false, src: CONFIG.src, out: CONFIG.out };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--check') opts.check = true;
    else if (a === '--src') opts.src = resolve(argv[++i]);
    else if (a === '--out') opts.out = resolve(argv[++i]);
    else throw new Error(`unknown argument: ${a}`);
  }
  return opts;
}

/** The generated copy of one source file: a marker comment, then the source unchanged. */
function render(sourceText, sourceLabel) {
  const sha = createHash('sha256').update(sourceText).digest('hex');
  const first = `GENERATED by adapters/codex/build.mjs from ${sourceLabel}, sha256 ${sha}.`;
  const second = 'Do not edit this copy. Edit the source, then run node adapters/codex/build.mjs.';
  const marker = sourceLabel.endsWith('.mjs')
    ? `// ${first}\n// ${second}\n\n`
    : sourceLabel.endsWith('.yaml')
      ? `# ${first}\n# ${second}\n\n`
      : `<!-- ${first}\n${second} -->\n\n`;
  return marker + sourceText;
}

/** Every output path and the content it should hold. */
function plan(src) {
  const files = new Map();
  for (const [dir, wanted] of Object.entries(CONFIG.copiedDirs)) {
    if (!existsSync(join(src, dir))) continue;
    for (const name of readdirSync(join(src, dir)).filter((n) => wanted.test(n)).sort()) {
      const text = readFileSync(join(src, dir, name), 'utf8');
      files.set(join(dir, name), render(text, `plugins/djinn/${dir}/${name}`));
    }
  }
  for (const single of CONFIG.singleFiles) {
    if (!existsSync(join(src, single))) continue;
    files.set(single, render(readFileSync(join(src, single), 'utf8'), `plugins/djinn/${single}`));
  }
  return files;
}

/** Copies in the copied folders that no source produces. */
function extras(out, files) {
  return Object.keys(CONFIG.copiedDirs).flatMap((dir) => {
    const full = join(out, dir);
    if (!existsSync(full)) return [];
    return readdirSync(full)
      .map((n) => join(dir, n))
      .filter((p) => !files.has(p));
  });
}

function main(argv) {
  const opts = parseArgs(argv);
  const files = plan(opts.src);
  const problems = [];
  for (const [path, want] of files) {
    const target = join(opts.out, path);
    const have = existsSync(target) ? readFileSync(target, 'utf8') : null;
    if (have === want) continue;
    if (opts.check) problems.push(`${have === null ? 'missing' : 'stale'}: ${relative(process.cwd(), target)}`);
    else {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, want);
    }
  }
  for (const path of extras(opts.out, files)) {
    const target = join(opts.out, path);
    if (opts.check) problems.push(`extra: ${relative(process.cwd(), target)}`);
    else rmSync(target);
  }
  if (opts.check) {
    if (problems.length === 0) {
      console.log(`codex build: up to date, ${files.size} files`);
      return 0;
    }
    console.log(problems.join('\n'));
    console.log(`codex build: ${problems.length} file(s) out of date. Run: node adapters/codex/build.mjs`);
    return 1;
  }
  console.log(`codex build: wrote ${files.size} files to ${relative(process.cwd(), opts.out) || '.'}`);
  return 0;
}

try {
  process.exitCode = main(process.argv.slice(2));
} catch (err) {
  console.error(`codex build: ${err.message}`);
  process.exitCode = 2;
}
