/**
 * Build the Codex plugin's copies of djinn's agent prompts and contracts.
 * Codex installs only adapters/codex/plugin/ into its cache, so a skill
 * there cannot read plugins/djinn/. This copies every agent file and
 * CONTRACTS.md in, each behind a generated-file comment that names its
 * source and the source's SHA-256. plugins/djinn stays the only copy
 * anyone edits. The Claude frontmatter is kept: each agent's own text
 * refers to it, and its tools line says which agents are read-only.
 *
 * Written by Claude Opus 5.5 for Donald, 2026-10-05. Status: tested, not
 * reviewed.
 *
 * Usage, from anywhere:
 *   node adapters/codex/build.mjs            write the copies
 *   node adapters/codex/build.mjs --check    exit 1 and name every copy
 *                                            that is stale, missing or extra
 * --src <dir> and --out <dir> override the two folders, for tests.
 *
 * @interacts  reads plugins/djinn/agents/*.md and plugins/djinn/CONTRACTS.md;
 *             writes adapters/codex/plugin/agents/*.md and
 *             adapters/codex/plugin/CONTRACTS.md, and deletes an agents/
 *             copy whose source is gone. Output is a pure function of the
 *             sources: no dates, no git calls.
 * @deps       node:fs, node:path, node:crypto, node:url. No packages.
 * @complexity O(f), f source files (32 today)
 * @alloc      one source and one output string per file, released per file
 */

import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '../..');

const CONFIG = {
  src: join(REPO, 'plugins/djinn'),
  out: join(HERE, 'plugin'),
  agentsDir: 'agents',
  contracts: 'CONTRACTS.md',
  agentFile: /\.md$/,
};

function parseArgs(argv) {
  const opts = { check: false, src: CONFIG.src, out: CONFIG.out };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--check') opts.check = true;
    else if (a === '--src') opts.src = resolve(argv[++i]);
    else if (a === '--out') opts.out = resolve(argv[++i]);
    else throw new Error(`unknown argument: ${a}`);
  }
  return opts;
}

/** The generated copy of one source file: a marker comment, then the source unchanged. */
function render(sourceText, sourceLabel) {
  const sha = createHash('sha256').update(sourceText).digest('hex');
  const marker =
    `<!-- GENERATED by adapters/codex/build.mjs from ${sourceLabel}, sha256 ${sha}.\n` +
    `Do not edit this copy. Edit the source, then run node adapters/codex/build.mjs. -->\n\n`;
  return marker + sourceText;
}

/** Every output path and the content it should hold. */
function plan(src) {
  const files = new Map();
  const agentsSrc = join(src, CONFIG.agentsDir);
  for (const name of readdirSync(agentsSrc).filter((n) => CONFIG.agentFile.test(n)).sort()) {
    const text = readFileSync(join(agentsSrc, name), 'utf8');
    files.set(join(CONFIG.agentsDir, name), render(text, `plugins/djinn/${CONFIG.agentsDir}/${name}`));
  }
  const contracts = readFileSync(join(src, CONFIG.contracts), 'utf8');
  files.set(CONFIG.contracts, render(contracts, `plugins/djinn/${CONFIG.contracts}`));
  return files;
}

/** Copies in out/agents that no source produces. */
function extras(out, files) {
  const dir = join(out, CONFIG.agentsDir);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .map((n) => join(CONFIG.agentsDir, n))
    .filter((p) => !files.has(p));
}

function main(argv) {
  const opts = parseArgs(argv);
  const files = plan(opts.src);
  const problems = [];
  for (const [path, want] of files) {
    const target = join(opts.out, path);
    const have = existsSync(target) ? readFileSync(target, 'utf8') : null;
    if (have === want) continue;
    if (opts.check) problems.push(`${have === null ? 'missing' : 'stale'}: ${relative(process.cwd(), target)}`);
    else {
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, want);
    }
  }
  for (const path of extras(opts.out, files)) {
    const target = join(opts.out, path);
    if (opts.check) problems.push(`extra: ${relative(process.cwd(), target)}`);
    else rmSync(target);
  }
  if (opts.check) {
    if (problems.length === 0) {
      console.log(`codex build: up to date, ${files.size} files`);
      return 0;
    }
    console.log(problems.join('\n'));
    console.log(`codex build: ${problems.length} file(s) out of date. Run: node adapters/codex/build.mjs`);
    return 1;
  }
  console.log(`codex build: wrote ${files.size} files to ${relative(process.cwd(), opts.out) || '.'}`);
  return 0;
}

try {
  process.exitCode = main(process.argv.slice(2));
} catch (err) {
  console.error(`codex build: ${err.message}`);
  process.exitCode = 2;
}
