/**
 * Draft a project's .djinn/config.yaml from djinn's template and what the
 * repo itself shows, so a new user's agent can set djinn up instead of
 * stopping at "no config". It fills only what it can read for certain (the
 * base branch, build and test commands from the project's own manifests,
 * the conventions files that exist, dependency manifests and lockfiles) and
 * leaves every other key at the template's default, comments kept.
 *
 * Without --write it prints the draft's facts and writes nothing; the
 * agent shows them and asks the owner. With --write it saves the file, and
 * it never overwrites an existing config.
 *
 * Written by Claude Opus 5.5 for Donald, 2026-10-05. Status: tested against
 * throwaway repos, not reviewed.
 *
 * Usage, from the repo root:
 *   node setup-project.mjs [--write] [--base <branch>] [--build <cmd|none>] [--test <cmd|none>]
 * Exit 0 on a draft or a write, 1 when it refuses (config exists, not a
 * repo root, no base branch found on --write), 2 for a usage error.
 *
 * @interacts  reads ../templates/config.yaml beside this script, the repo's
 *             package.json, pyproject.toml, Makefile and lockfiles, and git
 *             refs (read only); on --write creates .djinn/config.yaml
 * @deps       node:fs, node:path, node:child_process, node:url. No packages.
 * @complexity O(t + f), t template lines (about 300), f files probed (20)
 * @alloc      the template text and the draft, released at exit
 */

import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));

const CONFIG = {
  template: join(HERE, '..', 'templates', 'config.yaml'),
  target: join('.djinn', 'config.yaml'),
  knownBugs: join('.djinn', 'known-bugs.md'),
  baseCandidates: ['main', 'master', 'develop', 'trunk'],
  conventionFiles: ['AGENTS.md', 'CLAUDE.md', 'CONTRIBUTING.md'],
  manifests: ['package.json', 'pyproject.toml', 'requirements.txt', 'Cargo.toml', 'go.mod', 'Gemfile', 'composer.json'],
  lockfiles: ['package-lock.json', 'pnpm-lock.yaml', 'yarn.lock', 'bun.lockb', 'uv.lock', 'poetry.lock', 'Pipfile.lock', 'Cargo.lock', 'go.sum', 'Gemfile.lock', 'composer.lock'],
  nodeRunners: [['pnpm-lock.yaml', 'pnpm'], ['yarn.lock', 'yarn'], ['bun.lockb', 'bun'], ['package-lock.json', 'npm']],
};

// The generated-copy marker the Codex build puts on the template; dropped
// so a project's config never says "do not edit".
const MARKER = /^# (GENERATED by adapters\/codex\/build\.mjs|Do not edit this copy)\b.*\n/gm;

function git(repo, ...args) {
  const r = spawnSync('git', ['--no-optional-locks', '-C', repo, ...args], { encoding: 'utf8' });
  return r.status === 0 ? r.stdout.trim() : null;
}

/** The branch work merges into, and how it was found, or null. */
export function detectBase(repo) {
  const head = git(repo, 'symbolic-ref', '--quiet', '--short', 'refs/remotes/origin/HEAD');
  if (head && head.startsWith('origin/')) return { value: head.slice('origin/'.length), why: 'origin/HEAD' };
  for (const b of CONFIG.baseCandidates) {
    if (git(repo, 'show-ref', '--verify', '--quiet', `refs/heads/${b}`) !== null) return { value: b, why: 'local branch' };
    if (git(repo, 'show-ref', '--verify', '--quiet', `refs/remotes/origin/${b}`) !== null) return { value: b, why: 'origin branch' };
  }
  return null;
}

/** Build and test commands the project's own files name. */
export function detectCommands(repo) {
  const out = { build: null, test: null };
  const pkgPath = join(repo, 'package.json');
  if (existsSync(pkgPath)) {
    let scripts = {};
    try { scripts = JSON.parse(readFileSync(pkgPath, 'utf8')).scripts || {}; } catch { scripts = {}; }
    const runner = (CONFIG.nodeRunners.find(([lock]) => existsSync(join(repo, lock))) || [null, 'npm'])[1];
    if (scripts.build) out.build = { value: `${runner} run build`, why: 'package.json scripts.build' };
    if (scripts.test && !/no test specified/.test(scripts.test)) out.test = { value: `${runner} test`, why: 'package.json scripts.test' };
  }
  const py = join(repo, 'pyproject.toml');
  if (!out.test && existsSync(py) && /\[tool\.pytest|pytest/.test(readFileSync(py, 'utf8'))) {
    out.test = { value: existsSync(join(repo, 'uv.lock')) ? 'uv run pytest' : 'pytest', why: 'pyproject.toml names pytest' };
  }
  const make = join(repo, 'Makefile');
  if (existsSync(make)) {
    const text = readFileSync(make, 'utf8');
    if (!out.build && /^build:/m.test(text)) out.build = { value: 'make build', why: 'Makefile build target' };
    if (!out.test && /^test:/m.test(text)) out.test = { value: 'make test', why: 'Makefile test target' };
  }
  return out;
}

/** A YAML scalar for a command: none bare, anything else single quoted. */
export function yamlScalar(v) {
  return v === 'none' ? 'none' : `'${String(v).replace(/'/g, "''")}'`;
}

const list = (items) => (items.length ? `[${items.join(', ')}]` : '[]');

/** The facts for this repo, each with where it came from. */
export function draftFacts(repo, overrides = {}) {
  const base = overrides.base ? { value: overrides.base, why: 'given' } : detectBase(repo);
  const cmds = detectCommands(repo);
  const pick = (given, found) => (given ? { value: given, why: 'given' } : found || { value: 'none', why: 'nothing found' });
  return {
    base,
    build: pick(overrides.build, cmds.build),
    test: pick(overrides.test, cmds.test),
    conventions: CONFIG.conventionFiles.filter((f) => existsSync(join(repo, f))),
    knownBugs: existsSync(join(repo, CONFIG.knownBugs)) ? CONFIG.knownBugs : 'none',
    manifests: CONFIG.manifests.filter((f) => existsSync(join(repo, f))),
    lockfiles: CONFIG.lockfiles.filter((f) => existsSync(join(repo, f))),
  };
}

/** The config text: the template with the detected lines put in. */
export function draftText(template, facts, date) {
  let t = template.replace(MARKER, '').replace(/^\n+/, '');
  const swaps = [
    ['# Djinn Relay per-project config.\n# Copy to <project>/.djinn/config.yaml and fill in. Commit it.\n',
      `# Djinn Relay per-project config, drafted by djinn setup on ${date}.\n# Check it, change what is wrong, and commit it.\n`],
    ['base_branch: main\n', `base_branch: ${facts.base ? facts.base.value : 'main'}\n`],
    ['build_cmd: none\n', `build_cmd: ${yamlScalar(facts.build.value)}\n`],
    ['test_cmd: none\n', `test_cmd: ${yamlScalar(facts.test.value)}\n`],
    ['known_bugs_index: .djinn/known-bugs.md\n', `known_bugs_index: ${facts.knownBugs}\n`],
    ['conventions_files:\n  - CLAUDE.md\n', facts.conventions.length ? `conventions_files:\n${facts.conventions.map((f) => `  - ${f}\n`).join('')}` : 'conventions_files: []\n'],
    ['  manifests: []          #', `  manifests: ${list(facts.manifests)}          #`],
    ['  lockfiles: []          #', `  lockfiles: ${list(facts.lockfiles)}          #`],
  ];
  for (const [from, to] of swaps) {
    if (!t.includes(from)) throw new Error(`template changed: cannot find "${from.split('\n')[0]}"`);
    t = t.replace(from, to);
  }
  return t;
}

function main(argv) {
  const opts = { write: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--write') opts.write = true;
    else if (['--base', '--build', '--test'].includes(a) && argv[i + 1]) opts[a.slice(2)] = argv[++i];
    else {
      console.error('usage: node setup-project.mjs [--write] [--base <branch>] [--build <cmd|none>] [--test <cmd|none>]');
      return 2;
    }
  }
  const repo = process.cwd();
  const top = git(repo, 'rev-parse', '--show-toplevel');
  if (!top || realpathSync(top) !== realpathSync(repo)) {
    console.log('not changed: run this from the root of a git repo');
    return 1;
  }
  if (existsSync(join(repo, CONFIG.target))) {
    console.log(`already set up: ${CONFIG.target} exists; djinn uses it as it is`);
    return 0;
  }
  const facts = draftFacts(repo, opts);
  const show = (f) => `${f.value} (${f.why})`;
  const lines = [
    `djinn setup: ${opts.write ? 'writing' : 'draft, nothing written yet'}`,
    `base_branch: ${facts.base ? show(facts.base) : 'not found: name it with --base'}`,
    `build_cmd: ${show(facts.build)}`,
    `test_cmd: ${show(facts.test)}`,
    `conventions_files: ${facts.conventions.join(', ') || 'none found'}`,
    `known_bugs_index: ${facts.knownBugs}`,
    `deps: manifests ${facts.manifests.join(', ') || 'none'}; lockfiles ${facts.lockfiles.join(', ') || 'none'}`,
    'everything else: the template default (none), each key explained in the file',
  ];
  if (!opts.write) {
    console.log(lines.join('\n'));
    return 0;
  }
  if (!facts.base) {
    console.log(`${lines.join('\n')}\nnot written: no base branch found; pass --base <branch>`);
    return 1;
  }
  const text = draftText(readFileSync(CONFIG.template, 'utf8'), facts, new Date().toISOString().slice(0, 10));
  mkdirSync(join(repo, '.djinn'), { recursive: true });
  writeFileSync(join(repo, CONFIG.target), text, { flag: 'wx' });
  console.log(`${lines.join('\n')}\nwrote ${CONFIG.target}. Commit it with your next change.`);
  return 0;
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  try {
    process.exitCode = main(process.argv.slice(2));
  } catch (err) {
    console.log(`not changed: ${err.message}`);
    process.exitCode = 1;
  }
}
