/**
 * Tests for adapters/codex/build.mjs: the copies match their sources, the
 * check catches every way they drift, and the output does not depend on
 * when or where it runs.
 *
 * Written by Claude Opus 5.5 for Donald, 2026-10-05. Status: passing, not
 * reviewed.
 *
 * Run: node --test adapters/codex/tests/*.test.mjs
 *
 * @interacts  runs adapters/codex/build.mjs as a child process with --src
 *             and --out pointed at a temp folder
 * @deps       node:test, node:assert, node:child_process, node:fs, node:os,
 *             node:path, node:url. No packages.
 * @alloc      one temp folder per test, removed in its finally block
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const BUILD = resolve(dirname(fileURLToPath(import.meta.url)), '../build.mjs');

/** A temp source tree with two agents, a command and a contracts file; cleaned up after fn. */
function withTree(fn) {
  const root = mkdtempSync(join(tmpdir(), 'djinn-build-'));
  try {
    const src = join(root, 'src');
    const out = join(root, 'out');
    mkdirSync(join(src, 'agents'), { recursive: true });
    writeFileSync(join(src, 'agents', 'alpha.md'), '---\nname: alpha\nmodel: opus\n---\n\nAlpha body.\n');
    writeFileSync(join(src, 'agents', 'beta.md'), '---\nname: beta\n---\n\nBeta body.\n');
    mkdirSync(join(src, 'commands'), { recursive: true });
    writeFileSync(join(src, 'commands', 'gamma.md'), '---\nname: gamma\n---\n\nGamma steps.\n');
    writeFileSync(join(src, 'CONTRACTS.md'), '# Contracts\n');
    const run = (...args) => spawnSync('node', [BUILD, '--src', src, '--out', out, ...args], { cwd: root, encoding: 'utf8' });
    fn({ src, out, run });
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
}

test('build writes each source behind a marker, body unchanged', () => {
  withTree(({ out, run }) => {
    assert.equal(run().status, 0);
    const copy = readFileSync(join(out, 'agents', 'alpha.md'), 'utf8');
    assert.match(copy, /^<!-- GENERATED by adapters\/codex\/build\.mjs from plugins\/djinn\/agents\/alpha\.md, sha256 [0-9a-f]{64}\./);
    assert.ok(copy.endsWith('\n\n---\nname: alpha\nmodel: opus\n---\n\nAlpha body.\n'));
    assert.ok(existsSync(join(out, 'CONTRACTS.md')));
    assert.ok(existsSync(join(out, 'commands', 'gamma.md')));
  });
});

test('check passes right after a build', () => {
  withTree(({ run }) => {
    run();
    const r = run('--check');
    assert.equal(r.status, 0);
    assert.match(r.stdout, /up to date, 4 files/);
  });
});

test('check fails on an edited source, a missing copy and an extra copy', () => {
  withTree(({ src, out, run }) => {
    run();
    writeFileSync(join(src, 'agents', 'alpha.md'), 'changed\n');
    rmSync(join(out, 'agents', 'beta.md'));
    writeFileSync(join(out, 'agents', 'gone.md'), 'left behind\n');
    const r = run('--check');
    assert.equal(r.status, 1);
    assert.match(r.stdout, /^stale: .*agents\/alpha\.md$/m);
    assert.match(r.stdout, /^missing: .*agents\/beta\.md$/m);
    assert.match(r.stdout, /^extra: .*agents\/gone\.md$/m);
  });
});

test('check fails when a copy is edited by hand', () => {
  withTree(({ out, run }) => {
    run();
    writeFileSync(join(out, 'CONTRACTS.md'), 'hand edit\n');
    const r = run('--check');
    assert.equal(r.status, 1);
    assert.match(r.stdout, /^stale: .*CONTRACTS\.md$/m);
  });
});

test('check catches an extra copy in commands/ as well as agents/', () => {
  withTree(({ out, run }) => {
    run();
    writeFileSync(join(out, 'commands', 'old.md'), 'left behind\n');
    const r = run('--check');
    assert.equal(r.status, 1);
    assert.match(r.stdout, /^extra: .*commands\/old\.md$/m);
  });
});

test('build removes an extra copy and a rebuild changes nothing', () => {
  withTree(({ out, run }) => {
    run();
    writeFileSync(join(out, 'agents', 'gone.md'), 'left behind\n');
    run();
    assert.ok(!existsSync(join(out, 'agents', 'gone.md')));
    const first = readFileSync(join(out, 'agents', 'alpha.md'), 'utf8');
    run();
    assert.equal(readFileSync(join(out, 'agents', 'alpha.md'), 'utf8'), first);
  });
});

test('an unknown argument is a usage error, not a build', () => {
  withTree(({ out, run }) => {
    const r = run('--force');
    assert.equal(r.status, 2);
    assert.match(r.stderr, /unknown argument: --force/);
    assert.ok(!existsSync(out));
  });
});
